name: Build & Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Сборка CF
    uses: ShadobaAI/kafka-tools/.github/workflows/release-1c-artifacts.yml@main
    with:
      version_files: 'src/CommonModules/ОбновлениеИнформационнойБазыKafka/Module.bsl'
